[build]
    CI =''
    command = "npm run build"
    publish = "/build"
    base = "/"


[[redirects]]
    from ="/*"
    to ="/index.html"
    status= 200

    [build.environment]
  NODE_VERSION="14.0.0"